import { Company } from './company.model';
import { Country } from './country.model';
import { Genre } from './genre.mode';
import { Language } from './language.model';
import { Person } from './person.model';
import { Season } from './season.model';

export interface TvShow {
  backdrop_path?: string;
  created_by?: Person[];
  episode_run_time?: number[];
  first_air_date?: string;
  genres?: Genre[];
  homepage?: string;
  id?: number;
  in_production?: boolean;
  languages?: string[];
  last_air_date?: string;
  last_episode_to_air?: {
    air_date?: string;
    episode_number?: number;
    id?: number;
    name?: string;
    overview?: string;
    production_code?: string;
    season_number?: number;
    still_path?: string;
    vote_average?: number;
    vote_count?: number;
  };
  name?: string;
  next_episode_to_air?: number;
  networks?: Company[];
  number_of_episodes?: number;
  number_of_seasons?: number;
  origin_country?: string[];
  original_language?: string;
  original_name?: string;
  overview?: string;
  popularity?: number;
  poster_path?: string;
  production_companies?: Company[];
  production_countries?: Country[];
  seasons?: Season[];
  spoken_languages?: Language[];
  status?: string;
  tagline?: string;
  type?: string;
  vote_average?: number;
  vote_count?: number;
  rating?: number;
}
